### ISSUE TITLE
Start clowder admin implementation

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder2#433]
For beginning the admin, the following:

- [x] Add a field to the user model to determine admin or not
- [x] Have an initial admin.
- [x] Endpoints to set admins
- [x] Set proper permission level of the frontend pages and endpoint of the backend
- [x] Add this to backend auth routes. 
- [x] GUI for superadmin mode.

```[tasklist]
### Tasks
- [ ] https://github.com/clowder-framework/clowder2/issues/803
- [ ] https://github.com/clowder-framework/clowder2/issues/812
- [ ] https://github.com/clowder-framework/clowder2/issues/817
- [ ] https://github.com/clowder-framework/clowder2/issues/830
```

```[tasklist]
### Tasks
```

**Comment by longshuicy** [comment]
I can work on the GUI of the superadmin mode 
Does that mean we need a profile page as well?

**Comment by lmarini** [comment]
I don't think we need a profile page for this yet? We should think of some pages / functionality that requires admin before we start this.

**Comment by ddey2** [comment]
Created a task with 1st 3 checklists.

**Comment by ddey2** [comment]
I was thinking of the usecases which will require admin permission :

1. To delete datasets/files/folders which you don't own.
2. To view private datasets which you don't own (may be?)
3. To set others as admin, for which we need UI
4. Set permissions for different users in user groups. (similar to 3)

**Comment by ddey2** [comment]
5. reindexing indexes
6. metadata definition edition
7. approve users who have signed up
8. modify elasticsearch which adds a clause to filter it by permission

**Comment by ddey2** [comment]
Create 2 depends - 
1. which returns true if you're an admin
2. takes datasetId as parameter, and returns true if you have permission or an admin

**Comment by ddey2** [comment]
1. Super-admin: impersonate other
2. use keycloak roles for admin
