### ISSUE TITLE
License support

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#687]
Add the ability for users to pick a license for a dataset and include it in the dataset zipped download. Dataset license shows up on individual files. Unlike v1, don't provide ability to change license on individual files. It was confusing and wasn't used much.

Should we prompt users to accept license when download a dataset? Is this common/necessary? What about files?
```[tasklist]
### Tasks
- [ ] https://github.com/clowder-framework/clowder2/issues/945
- [ ] https://github.com/clowder-framework/clowder2/issues/946
- [ ] https://github.com/clowder-framework/clowder2/issues/947
```
