### ISSUE TITLE
Add admin dependency in all functions

### ISSUE THREAD

**Issue by ddey2** [clowder-framework/clowder2#817]
```[tasklist]
### Tasks
- [x] To set others as admin, (we need UI too)
- [x] metadata definition edition
- [x] modify elasticsearch which adds a clause to filter it by permission
- [x] modify dataset permission to take into account if you're an admin, modify the current dependency
```

```

**Comment by ddey2** [comment]
make an issue for approving users who have signed up
